<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Carousel_1slide</name>
   <tag></tag>
   <elementGuidId>85175056-241d-41bb-b816-e135441b4e07</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>score-content-spot</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Pane 1
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel-55afd46a-e510-4b6c-909e-fa1c1026acd4&quot;)/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;item score-carousel-pane active&quot;]/div[@class=&quot;score-carousel-pane-body&quot;]/div[@class=&quot;score-content-spot&quot;]</value>
   </webElementProperties>
</WebElementEntity>
