<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_scWebEditRibbon</name>
   <tag></tag>
   <elementGuidId>2f86aebf-1ed5-4de7-ba9d-6b934f59a356</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scWebEditRibbon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sitecore/client/Applications/ExperienceEditor/Ribbon.aspx?sc_content=core&amp;ribbonId=%7B570A52B6-6755-461A-8052-5B95EF766F74%7D&amp;itemId=%7B9A10DA0B-93FA-40A8-84B2-356DA03A44F9%7D&amp;deviceId=%7BFE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3%7D&amp;database=master&amp;mode=edit&amp;url=%2F%3Fsc_mode%3Dedit%26sc_itemid%3D%257b9A10DA0B-93FA-40A8-84B2-356DA03A44F9%257d%26sc_version%3D1%26sc_lang%3Den%26sc_site%3Dbootstrapui&amp;lang=en&amp;pageSite=bootstrapui&amp;version=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scSpeakWebEditRibbon scWebEditRibbon scFixedRibbon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scWebEditRibbon&quot;)</value>
   </webElementProperties>
</WebElementEntity>
