<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Content Editor</name>
   <tag></tag>
   <elementGuidId>62e015de-f91d-46b3-a2ee-7f02f143df70</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-launchpad-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Content Editor
                  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sc&quot;]/div[@class=&quot;sc-list&quot;]/div[@class=&quot;container-narrow&quot;]/section[@class=&quot;sc-applicationContent&quot;]/section[@class=&quot;sc-applicationContent-main&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;sc-launchpad&quot;]/div[@class=&quot;sc-launchpad-group&quot;]/div[@class=&quot;sc-launchpad-group-row&quot;]/a[@class=&quot;sc-launchpad-item&quot;]/span[@class=&quot;sc-launchpad-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
